name: Deploy Documentation to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build specs
        run: |
          npm run build

      - name: Build documentation
        run: |
          npm install -g @open-rpc/generator
          open-rpc-generator generate -c open-rpc-generator-config-doc.json    
          cp img/*.* build/docs/gatsby/src/images/
          ls build/docs/gatsby
          cd build/docs/gatsby
          pwd
          npm install
          npm install -g gatsby-cli
          sed -i "s,https://raw.githubusercontent.com/open-rpc/design/master/icons/open-rpc-logo-noText/open-rpc-logo-noText%20(PNG)/256x256.png,https://downloads.quantumcoin.org/quantum-coin-icon.png,g" src/pages/index.tsx
          sed -i "s,https://raw.githubusercontent.com/open-rpc/design/master/icons/open-rpc-logo-noText/open-rpc-logo-noText%20(PNG)/256x256.png,https://downloads.quantumcoin.org/quantum-coin-icon.png,g" gatsby-config.js
          sed -i "s,siteUrl: 'https://open-rpc.org',siteUrl: 'https://quantumcoin.org',g" gatsby-config.js
          sed -i "s,src/images/gatsby-icon.png,src/images/favicon.ico,g" gatsby-config.js
          sed -i "s,name: 'home',name: 'Home',g" gatsby-config.js
          gatsby build       
          ls
          ls public/
          ls src/pages
          ls src/    

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/gatsby/public

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
