name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Test build website
        run: |
          npm run build
          npm install -g @open-rpc/generator
          open-rpc-generator generate -c open-rpc-generator-config.json    
          cp img/*.* build/docs/gatsby/src/images/
          ls build/docs/gatsby
          cd build/docs/gatsby
          pwd
          npm install
          npm install -g gatsby-cli
          sed -i "s,https://raw.githubusercontent.com/open-rpc/design/master/icons/open-rpc-logo-noText/open-rpc-logo-noText%20(PNG)/256x256.png,https://downloads.quantumcoin.org/quantum-coin-icon.png,g" src/pages/index.tsx
          sed -i "s,https://raw.githubusercontent.com/open-rpc/design/master/icons/open-rpc-logo-noText/open-rpc-logo-noText%20(PNG)/256x256.png,https://downloads.quantumcoin.org/quantum-coin-icon.png,g" gatsby-config.js
          sed -i "s,siteUrl: 'https://open-rpc.org',siteUrl: 'https://quantumcoin.org',g" gatsby-config.js
          sed -i "s,src/images/gatsby-icon.png,src/images/favicon.ico,g" gatsby-config.js
          sed -i "s,name: 'home',name: 'Home',g" gatsby-config.js
          gatsby build       
          ls
          ls public/
          ls src/pages
          ls src/
